name: share
description: Добавить или изменить информацию о раздаче ресурсов
labels: 
  - Раздача
body:
  - type: dropdown
    id: change-kind
    attributes:
      label: Тип изменения
      options:
        - Я хочу добавить информацию о раздаче ресурсов 
        - Я хочу изменить информацию о раздаче ресурсов
        - Другое
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Описание
      description: Здесь опишите ресурс или проблему
    validations:
      required: true